/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tech_anapad_modela_util_i2c_I2CNative */

#ifndef _Included_tech_anapad_modela_util_i2c_I2CNative
#define _Included_tech_anapad_modela_util_i2c_I2CNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tech_anapad_modela_util_i2c_I2CNative
 * Method:    start
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_tech_anapad_modela_util_i2c_I2CNative_start(JNIEnv*, jclass, jint);

/*
 * Class:     tech_anapad_modela_util_i2c_I2CNative
 * Method:    stop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_tech_anapad_modela_util_i2c_I2CNative_stop(JNIEnv*, jclass, jint);

/*
 * Class:     tech_anapad_modela_util_i2c_I2CNative
 * Method:    writeByte
 * Signature: (ISB)V
 */
JNIEXPORT void JNICALL Java_tech_anapad_modela_util_i2c_I2CNative_writeByte(JNIEnv*, jclass, jint, jshort, jbyte);

/*
 * Class:     tech_anapad_modela_util_i2c_I2CNative
 * Method:    writeRegisterByte
 * Signature: (ISSBZ)V
 */
JNIEXPORT void JNICALL Java_tech_anapad_modela_util_i2c_I2CNative_writeRegisterByte(JNIEnv*, jclass, jint, jshort,
        jshort, jbyte, jboolean);

/*
 * Class:     tech_anapad_modela_util_i2c_I2CNative
 * Method:    writeRegisterBytes
 * Signature: (ISS[BZ)V
 */
JNIEXPORT void JNICALL Java_tech_anapad_modela_util_i2c_I2CNative_writeRegisterBytes(JNIEnv*, jclass, jint, jshort,
        jshort, jbyteArray, jboolean);

/*
 * Class:     tech_anapad_modela_util_i2c_I2CNative
 * Method:    readByte
 * Signature: (IS)B
 */
JNIEXPORT jbyte JNICALL Java_tech_anapad_modela_util_i2c_I2CNative_readByte(JNIEnv*, jclass, jint, jshort);

/*
 * Class:     tech_anapad_modela_util_i2c_I2CNative
 * Method:    readRegisterByte
 * Signature: (ISSZ)B
 */
JNIEXPORT jbyte JNICALL Java_tech_anapad_modela_util_i2c_I2CNative_readRegisterByte(JNIEnv*, jclass, jint, jshort,
        jshort, jboolean);

/*
 * Class:     tech_anapad_modela_util_i2c_I2CNative
 * Method:    readRegisterBytes
 * Signature: (ISSIZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_tech_anapad_modela_util_i2c_I2CNative_readRegisterBytes(JNIEnv*, jclass, jint, jshort,
        jshort, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
