/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tech_anapad_modela_jni_I2CInterface */

#ifndef _Included_tech_anapad_modela_jni_I2CInterface
#define _Included_tech_anapad_modela_jni_I2CInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tech_anapad_modela_jni_I2CInterface
 * Method:    i2cStart
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_tech_anapad_modela_jni_I2CInterface_i2cStart(JNIEnv*, jclass, jstring);

/*
 * Class:     tech_anapad_modela_jni_I2CInterface
 * Method:    i2cStop
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_tech_anapad_modela_jni_I2CInterface_i2cStop(JNIEnv*, jclass, jstring);

/*
 * Class:     tech_anapad_modela_jni_I2CInterface
 * Method:    i2cWriteByte
 * Signature: (ISB)V
 */
JNIEXPORT void JNICALL Java_tech_anapad_modela_jni_I2CInterface_i2cWriteByte(JNIEnv*, jclass, jint, jshort, jbyte);

/*
 * Class:     tech_anapad_modela_jni_I2CInterface
 * Method:    i2cWriteRegisterByte
 * Signature: (ISSBZ)V
 */
JNIEXPORT void JNICALL Java_tech_anapad_modela_jni_I2CInterface_i2cWriteRegisterByte(JNIEnv*, jclass, jint, jshort,
        jshort, jbyte, jboolean);

/*
 * Class:     tech_anapad_modela_jni_I2CInterface
 * Method:    i2cWriteRegisterBytes
 * Signature: (ISS[BZ)V
 */
JNIEXPORT void JNICALL Java_tech_anapad_modela_jni_I2CInterface_i2cWriteRegisterBytes(JNIEnv*, jclass, jint, jshort,
        jshort, jbyteArray, jboolean);

/*
 * Class:     tech_anapad_modela_jni_I2CInterface
 * Method:    i2cReadByte
 * Signature: (IS)B
 */
JNIEXPORT jbyte JNICALL Java_tech_anapad_modela_jni_I2CInterface_i2cReadByte(JNIEnv*, jclass, jint, jshort);

/*
 * Class:     tech_anapad_modela_jni_I2CInterface
 * Method:    i2cReadRegisterByte
 * Signature: (ISSZ)B
 */
JNIEXPORT jbyte JNICALL Java_tech_anapad_modela_jni_I2CInterface_i2cReadRegisterByte(JNIEnv*, jclass, jint, jshort,
        jshort, jboolean);

/*
 * Class:     tech_anapad_modela_jni_I2CInterface
 * Method:    i2cReadRegisterBytes
 * Signature: (ISSIZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_tech_anapad_modela_jni_I2CInterface_i2cReadRegisterBytes(JNIEnv*, jclass, jint,
        jshort, jshort, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
